# Generated by Django 3.0.5 on 2020-08-26 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200731_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='quiz end time'),
            preserve_default=False,
        ),
    ]
