# Generated by Django 3.0.5 on 2020-04-29 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=75, verbose_name='description')),
                ('question', models.FileField(upload_to='assignment_questions/')),
                ('max_marks', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='classroom id')),
                ('room_number', models.IntegerField(blank=True, verbose_name='room number')),
                ('course_name', models.CharField(max_length=60, verbose_name='course name')),
                ('student_id', models.ManyToManyField(related_name='attending_classes', to='accounts.Student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taking_classes', to='accounts.Teacher')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='notes/')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='classroom.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_file', models.FileField(upload_to='assignment_submission')),
                ('marks', models.PositiveIntegerField()),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='classroom.Assignment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_solutions', to='accounts.Student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classroom.Classroom'),
        ),
    ]
