# Generated by Django 3.0.5 on 2020-04-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200430_0053'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='joining_permission',
            field=models.BooleanField(default=True, verbose_name='joining permission'),
        ),
        migrations.CreateModel(
            name='JoinQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awaiting_join_requests', to='classroom.Classroom')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_request_queued', to='accounts.Student')),
            ],
        ),
    ]
