# Generated by Django 3.0.5 on 2020-05-09 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinQueue',
            new_name='JoinRequests',
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns_solution', to=settings.AUTH_USER_MODEL),
        ),
    ]
