# Generated by Django 3.0.5 on 2020-05-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200509_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomstudents',
            name='classroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classroom.Classroom'),
        ),
    ]
