# Generated by Django 3.0.5 on 2020-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_assignment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='remarks',
            field=models.CharField(default=1, max_length=30, verbose_name='remark'),
            preserve_default=False,
        ),
    ]
