# Generated by Django 3.0.5 on 2020-05-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_assignmentsubmission_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='remarks',
        ),
    ]
