# Generated by Django 3.0.5 on 2020-05-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_remove_assignmentsubmission_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='marks',
        ),
        migrations.CreateModel(
            name='AssignmentGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('publish', models.BooleanField(default=False, verbose_name='publish')),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classroom.AssignmentSubmission')),
            ],
        ),
    ]
