# Generated by Django 3.0.5 on 2020-05-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20200519_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AssignmentGrades',
        ),
    ]
